# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: sudo apt-get install -y bc wget build-essential bzr cvs git mercurial rsync subversion
  displayName: Install dependencies
- script: ./build.sh
  displayName: Run builder
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/toolchain'
    archiveType: 'tar'
    tarCompression: 'none'
    archiveFile: '$(Build.ArtifactStagingDirectory)/rs97_toolchain-$(Build.BuildId).tar'
- task: PublishBuildArtifacts@1